spring:
  config:
    import: optional:classpath:secret.properties
  application:
    name: taskflow
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: YOUR_DB_USERNAME
    password: YOUR_DB_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  server:
    port: 8080
